#!/bin/sh

OPTIONS=""	# GETTY_OPTIONS
BAUDRATE=115200	# GETTY_BAUDRATE
TERM="vt100"	# GETTY_TERM
CONSOLE=""	# GETTY CONSOLE

sed -i -e '/run.sh/d' /etc/inittab

findconsole()
{
  cons="$1"
  rv=0

  if [ -z "${cons}" ]; then
    return 0
  fi

  for con in ${cons}; do
    if [ "${con}" != "tty" -a "${con}" != "tty0" -a -e "/dev/${con}" ]; then
	echo "Found console ${con}"
	echo "${con}::respawn:/sbin/getty -n -l /run.sh ${OPTIONS} ${con} ${BAUDRATE} ${TERM}" >> /etc/inittab
	rv=1
    fi
  done
  return ${rv}
}

findconsole "${CONSOLE}"
found=$?
if [ ${found} -eq 0 ]; then
  findconsole "$(cat /proc/consoles | awk '{ print $1 }')"
  found=$?
  if [ ${found} -eq 0 ]; then
    findconsole "$(cat /sys/class/tty/console/active)"
    found=$?
    if [ ${found} -eq 0 ]; then
      findconsole "console"
      found=$?
    fi
  fi
fi

if [ ${found} -eq 0 ]; then
    echo "WARNING: no useful console"
    echo "command line: $(cat /proc/cmdline)"
    echo "consoles: $(cat /proc/consoles)"
    echo "active: $(cat /sys/class/tty/console/active)"

    exec /run.sh
fi

kill -SIGHUP 1
